# Site
repository: devforlove/devforlove.github.io

# Personal info
name: 정인욱
title: 더블다운인터액티브 서버 개발자
email: inwookgusa@gmail.com
website: https://wooktech.tistory.com

# Additional icon links
additional_links:
  - title: Tech Blog
    icon: fab fa-blogger
    url: https://wooktech.tistory.com

# Social links
github_username: devforlove

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java, String 기반 3년차 개발자로써, HADA 조기 어플리케이션 개발에 참여하여 설계 및 개발을 하였고, 
  1000만 사용자를 가진 Double Down Casino 에서 기능 개발 및 성능 최적화를 담당하였습니다. \
  <mark>어플리케이션의 지속 가능성, 확장성 있는 설계</mark>를 중요하게 생각하기 때문에, 
  더 좋은 어플리케이션의 아키텍처와 테스트 코드에 대해 고민합니다. 그리고 고민한 결과를 팀원들과 공유하여 더 좋은 개발 문화를 만드는 것에 관심이 많습니다. \
  특히 <mark>테스트 코드</mark>를 중요하게 생각하기 생각하며, 전 직장에선 테스트 코드 커버리지를 90% 이상 유지하였습니다. 
  그리고 더 좋은 테스트 코드를 작성하기 위해 항상 고민합니다. \
  마주했던 문제는 더 자세한 학습과, 명확한 결과 도출을 위해, 개인 블로그에 <mark>상세히 기록</mark>하고 있습니다. 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag