# Site
repository: devforlove/devforlove.github.io

# Personal info
name: 정인욱
title: 서버 개발자
email: inwookgusa@gmail.com
website: https://wooktech.tistory.com

# Additional icon links
additional_links:
  - title: Tech Blog
    icon: fab fa-blogger
    url: https://wooktech.tistory.com

# Social links
github_username: devforlove

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java, Spring 기반 4년차 개발자로써, HADA 서비스 초기 어플리케이션 개발에 참여하여 설계 및 개발을 하였고, 
  1000만 사용자를 가진 Double Down Casino 에서 기능 개발 및 성능 최적화를 담당하였습니다. \
  성능 모니터링을 위해 Intellij Profiler, Ngrinder, Prometheus와 같은 도구를 사용하며, 기존 코드와 아키텍처의 문제를 파악 후 개선하여 메모리 사용량을 감소시키고 지연 시간을 최소화하여 TPS를 증가시키는 등 <mark>사용자 경험(UX)</mark>을 향상시키는 데 주력했습니다. \
  특히 <mark>테스트 코드와 확장성 있는 시스템 설계</mark>를 중요하게 생각하기 생각하기 때문에, 정리한 문서를 기반으로 팀원들과 고민하여 높은 품질의 코드를 만드는데 관심이 많습니다. 그 과정에서 테스트 코드 커버리지를 항상 100%에 가까이 유지하려고 노력하였습니다. \
  마주했던 문제는 더 자세한 학습과, 명확한 결과 도출을 위해, 개인 블로그에 <mark>상세히 기록</mark>하고 있습니다. 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag